// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: proto/espmsg.proto

//import "nanopb.proto";

package espmsg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EspMsgType int32

const (
	EspMsgType_OpInvalid   EspMsgType = 0
	EspMsgType_OPSetPerf   EspMsgType = 1
	EspMsgType_OPSetDuty   EspMsgType = 2
	EspMsgType_OPGetStatus EspMsgType = 3
)

// Enum value maps for EspMsgType.
var (
	EspMsgType_name = map[int32]string{
		0: "OpInvalid",
		1: "OPSetPerf",
		2: "OPSetDuty",
		3: "OPGetStatus",
	}
	EspMsgType_value = map[string]int32{
		"OpInvalid":   0,
		"OPSetPerf":   1,
		"OPSetDuty":   2,
		"OPGetStatus": 3,
	}
)

func (x EspMsgType) Enum() *EspMsgType {
	p := new(EspMsgType)
	*p = x
	return p
}

func (x EspMsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EspMsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_espmsg_proto_enumTypes[0].Descriptor()
}

func (EspMsgType) Type() protoreflect.EnumType {
	return &file_proto_espmsg_proto_enumTypes[0]
}

func (x EspMsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EspMsgType.Descriptor instead.
func (EspMsgType) EnumDescriptor() ([]byte, []int) {
	return file_proto_espmsg_proto_rawDescGZIP(), []int{0}
}

type SetPerf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Temp float64 `protobuf:"fixed64,1,opt,name=temp,proto3" json:"temp,omitempty"`
	Load float64 `protobuf:"fixed64,2,opt,name=load,proto3" json:"load,omitempty"`
}

func (x *SetPerf) Reset() {
	*x = SetPerf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_espmsg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetPerf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPerf) ProtoMessage() {}

func (x *SetPerf) ProtoReflect() protoreflect.Message {
	mi := &file_proto_espmsg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPerf.ProtoReflect.Descriptor instead.
func (*SetPerf) Descriptor() ([]byte, []int) {
	return file_proto_espmsg_proto_rawDescGZIP(), []int{0}
}

func (x *SetPerf) GetTemp() float64 {
	if x != nil {
		return x.Temp
	}
	return 0
}

func (x *SetPerf) GetLoad() float64 {
	if x != nil {
		return x.Load
	}
	return 0
}

type SetDuty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Duty float64 `protobuf:"fixed64,1,opt,name=duty,proto3" json:"duty,omitempty"`
}

func (x *SetDuty) Reset() {
	*x = SetDuty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_espmsg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetDuty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDuty) ProtoMessage() {}

func (x *SetDuty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_espmsg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDuty.ProtoReflect.Descriptor instead.
func (*SetDuty) Descriptor() ([]byte, []int) {
	return file_proto_espmsg_proto_rawDescGZIP(), []int{1}
}

func (x *SetDuty) GetDuty() float64 {
	if x != nil {
		return x.Duty
	}
	return 0
}

type EspMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Operation EspMsgType `protobuf:"varint,1,opt,name=operation,proto3,enum=espmsg.EspMsgType" json:"operation,omitempty"`
	Id        int32      `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are assignable to Op:
	//	*EspMsg_Perf
	//	*EspMsg_Duty
	Op isEspMsg_Op `protobuf_oneof:"op"`
}

func (x *EspMsg) Reset() {
	*x = EspMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_espmsg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EspMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EspMsg) ProtoMessage() {}

func (x *EspMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_espmsg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EspMsg.ProtoReflect.Descriptor instead.
func (*EspMsg) Descriptor() ([]byte, []int) {
	return file_proto_espmsg_proto_rawDescGZIP(), []int{2}
}

func (x *EspMsg) GetOperation() EspMsgType {
	if x != nil {
		return x.Operation
	}
	return EspMsgType_OpInvalid
}

func (x *EspMsg) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (m *EspMsg) GetOp() isEspMsg_Op {
	if m != nil {
		return m.Op
	}
	return nil
}

func (x *EspMsg) GetPerf() *SetPerf {
	if x, ok := x.GetOp().(*EspMsg_Perf); ok {
		return x.Perf
	}
	return nil
}

func (x *EspMsg) GetDuty() *SetDuty {
	if x, ok := x.GetOp().(*EspMsg_Duty); ok {
		return x.Duty
	}
	return nil
}

type isEspMsg_Op interface {
	isEspMsg_Op()
}

type EspMsg_Perf struct {
	Perf *SetPerf `protobuf:"bytes,3,opt,name=Perf,proto3,oneof"`
}

type EspMsg_Duty struct {
	Duty *SetDuty `protobuf:"bytes,4,opt,name=Duty,proto3,oneof"`
}

func (*EspMsg_Perf) isEspMsg_Op() {}

func (*EspMsg_Duty) isEspMsg_Op() {}

type EspResultStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Temp float64 `protobuf:"fixed64,1,opt,name=temp,proto3" json:"temp,omitempty"`
	Load float64 `protobuf:"fixed64,2,opt,name=load,proto3" json:"load,omitempty"`
	Duty int32   `protobuf:"varint,3,opt,name=duty,proto3" json:"duty,omitempty"`
	Rpm  int32   `protobuf:"varint,4,opt,name=rpm,proto3" json:"rpm,omitempty"`
}

func (x *EspResultStatus) Reset() {
	*x = EspResultStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_espmsg_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EspResultStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EspResultStatus) ProtoMessage() {}

func (x *EspResultStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_espmsg_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EspResultStatus.ProtoReflect.Descriptor instead.
func (*EspResultStatus) Descriptor() ([]byte, []int) {
	return file_proto_espmsg_proto_rawDescGZIP(), []int{3}
}

func (x *EspResultStatus) GetTemp() float64 {
	if x != nil {
		return x.Temp
	}
	return 0
}

func (x *EspResultStatus) GetLoad() float64 {
	if x != nil {
		return x.Load
	}
	return 0
}

func (x *EspResultStatus) GetDuty() int32 {
	if x != nil {
		return x.Duty
	}
	return 0
}

func (x *EspResultStatus) GetRpm() int32 {
	if x != nil {
		return x.Rpm
	}
	return 0
}

type EspResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Operation EspMsgType `protobuf:"varint,1,opt,name=operation,proto3,enum=espmsg.EspMsgType" json:"operation,omitempty"`
	Id        int32      `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are assignable to Op:
	//	*EspResult_Status
	Op isEspResult_Op `protobuf_oneof:"op"`
}

func (x *EspResult) Reset() {
	*x = EspResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_espmsg_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EspResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EspResult) ProtoMessage() {}

func (x *EspResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_espmsg_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EspResult.ProtoReflect.Descriptor instead.
func (*EspResult) Descriptor() ([]byte, []int) {
	return file_proto_espmsg_proto_rawDescGZIP(), []int{4}
}

func (x *EspResult) GetOperation() EspMsgType {
	if x != nil {
		return x.Operation
	}
	return EspMsgType_OpInvalid
}

func (x *EspResult) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (m *EspResult) GetOp() isEspResult_Op {
	if m != nil {
		return m.Op
	}
	return nil
}

func (x *EspResult) GetStatus() *EspResultStatus {
	if x, ok := x.GetOp().(*EspResult_Status); ok {
		return x.Status
	}
	return nil
}

type isEspResult_Op interface {
	isEspResult_Op()
}

type EspResult_Status struct {
	Status *EspResultStatus `protobuf:"bytes,3,opt,name=Status,proto3,oneof"`
}

func (*EspResult_Status) isEspResult_Op() {}

var File_proto_espmsg_proto protoreflect.FileDescriptor

var file_proto_espmsg_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x73, 0x70, 0x6d, 0x73, 0x67, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x65, 0x73, 0x70, 0x6d, 0x73, 0x67, 0x22, 0x31, 0x0a, 0x07,
	0x53, 0x65, 0x74, 0x50, 0x65, 0x72, 0x66, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x6d, 0x70, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x74, 0x65, 0x6d, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x6c,
	0x6f, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x6c, 0x6f, 0x61, 0x64, 0x22,
	0x1d, 0x0a, 0x07, 0x53, 0x65, 0x74, 0x44, 0x75, 0x74, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x75,
	0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x64, 0x75, 0x74, 0x79, 0x22, 0x9e,
	0x01, 0x0a, 0x06, 0x45, 0x73, 0x70, 0x4d, 0x73, 0x67, 0x12, 0x30, 0x0a, 0x09, 0x6f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x65,
	0x73, 0x70, 0x6d, 0x73, 0x67, 0x2e, 0x45, 0x73, 0x70, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x25, 0x0a, 0x04, 0x50,
	0x65, 0x72, 0x66, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x65, 0x73, 0x70, 0x6d,
	0x73, 0x67, 0x2e, 0x53, 0x65, 0x74, 0x50, 0x65, 0x72, 0x66, 0x48, 0x00, 0x52, 0x04, 0x50, 0x65,
	0x72, 0x66, 0x12, 0x25, 0x0a, 0x04, 0x44, 0x75, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x65, 0x73, 0x70, 0x6d, 0x73, 0x67, 0x2e, 0x53, 0x65, 0x74, 0x44, 0x75, 0x74,
	0x79, 0x48, 0x00, 0x52, 0x04, 0x44, 0x75, 0x74, 0x79, 0x42, 0x04, 0x0a, 0x02, 0x6f, 0x70, 0x22,
	0x5f, 0x0a, 0x0f, 0x45, 0x73, 0x70, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x04, 0x74, 0x65, 0x6d, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x75,
	0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x64, 0x75, 0x74, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x72, 0x70, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x72, 0x70, 0x6d,
	0x22, 0x86, 0x01, 0x0a, 0x09, 0x45, 0x73, 0x70, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x30,
	0x0a, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x12, 0x2e, 0x65, 0x73, 0x70, 0x6d, 0x73, 0x67, 0x2e, 0x45, 0x73, 0x70, 0x4d, 0x73,
	0x67, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x31, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x17, 0x2e, 0x65, 0x73, 0x70, 0x6d, 0x73, 0x67, 0x2e, 0x45, 0x73, 0x70, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x48, 0x00, 0x52, 0x06, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x42, 0x04, 0x0a, 0x02, 0x6f, 0x70, 0x2a, 0x4a, 0x0a, 0x0a, 0x45, 0x73, 0x70,
	0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0d, 0x0a, 0x09, 0x4f, 0x70, 0x49, 0x6e, 0x76,
	0x61, 0x6c, 0x69, 0x64, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x4f, 0x50, 0x53, 0x65, 0x74, 0x50,
	0x65, 0x72, 0x66, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x4f, 0x50, 0x53, 0x65, 0x74, 0x44, 0x75,
	0x74, 0x79, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x4f, 0x50, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x10, 0x03, 0x42, 0x0c, 0x5a, 0x0a, 0x70, 0x6b, 0x67, 0x2f, 0x65, 0x73, 0x70,
	0x6d, 0x73, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_espmsg_proto_rawDescOnce sync.Once
	file_proto_espmsg_proto_rawDescData = file_proto_espmsg_proto_rawDesc
)

func file_proto_espmsg_proto_rawDescGZIP() []byte {
	file_proto_espmsg_proto_rawDescOnce.Do(func() {
		file_proto_espmsg_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_espmsg_proto_rawDescData)
	})
	return file_proto_espmsg_proto_rawDescData
}

var file_proto_espmsg_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_espmsg_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_espmsg_proto_goTypes = []interface{}{
	(EspMsgType)(0),         // 0: espmsg.EspMsgType
	(*SetPerf)(nil),         // 1: espmsg.SetPerf
	(*SetDuty)(nil),         // 2: espmsg.SetDuty
	(*EspMsg)(nil),          // 3: espmsg.EspMsg
	(*EspResultStatus)(nil), // 4: espmsg.EspResultStatus
	(*EspResult)(nil),       // 5: espmsg.EspResult
}
var file_proto_espmsg_proto_depIdxs = []int32{
	0, // 0: espmsg.EspMsg.operation:type_name -> espmsg.EspMsgType
	1, // 1: espmsg.EspMsg.Perf:type_name -> espmsg.SetPerf
	2, // 2: espmsg.EspMsg.Duty:type_name -> espmsg.SetDuty
	0, // 3: espmsg.EspResult.operation:type_name -> espmsg.EspMsgType
	4, // 4: espmsg.EspResult.Status:type_name -> espmsg.EspResultStatus
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_espmsg_proto_init() }
func file_proto_espmsg_proto_init() {
	if File_proto_espmsg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_espmsg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetPerf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_espmsg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetDuty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_espmsg_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EspMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_espmsg_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EspResultStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_espmsg_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EspResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_espmsg_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*EspMsg_Perf)(nil),
		(*EspMsg_Duty)(nil),
	}
	file_proto_espmsg_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*EspResult_Status)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_espmsg_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_espmsg_proto_goTypes,
		DependencyIndexes: file_proto_espmsg_proto_depIdxs,
		EnumInfos:         file_proto_espmsg_proto_enumTypes,
		MessageInfos:      file_proto_espmsg_proto_msgTypes,
	}.Build()
	File_proto_espmsg_proto = out.File
	file_proto_espmsg_proto_rawDesc = nil
	file_proto_espmsg_proto_goTypes = nil
	file_proto_espmsg_proto_depIdxs = nil
}
